version: '3.8'

services:
  fastapi:
    build: 
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/code/app  # 自動掛載本機的 app 目錄到容器內的 /app
    environment:
      - ENV=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"